[build]
  [build.environment]
    SECRETS_SCAN_OMIT_KEYS = "NETWORK,PRICE_SINGLE,PRICE_BATCH,PAYMENT_ADDRESS,FACILITATOR_URL,BASE_URL,CDP_PROJECT_ID"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
